# SPDX-FileCopyrightText: 2023 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# For now, assume .NET flavor, as all the projects use .NET.
# Maybe, in the future, we could have this parameterized.

name: Lint

on:
  # Support reusing this workflow ...
  workflow_call:
  # .. and use it for this very repository itself.
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Some linters support auto-correct, but we don't use that.
# So, these are only allowed to inspect the source and post the results.

permissions:
  contents: read
  pull-requests: write

jobs:
  REUSE:
    uses: dorssel/workflows/.github/workflows/REUSE.yml@main

  MegaLinterNET:
    uses: dorssel/workflows/.github/workflows/mega-linter-dotnet.yml@main
