# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: MIT

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CheckSDK

on:
  # Support reusing this workflow ...
  workflow_call:
  # No need to run this workflow on this repo itself.

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: martincostello/update-dotnet-sdk@v3

        with:
          labels: dependencies
          repo-token: ${{ secrets.GITHUB_TOKEN }}
